source 'https://rubygems.org'

gem 'rails', '3.2.12'

gem 'sqlite3'
gem 'mysql2', '0.3.11'

gem 'jquery-rails'

gem 'thin'
gem 'exceptional', "2.0.33"                               #exception notifications

group :assets do
  gem 'sass-rails',   '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.2.5'
end

group :development do
  gem 'sunspot_solr', '1.3.3'
end

gem 'artfully_ose', :path => "../artful.ly/lib/artfully_ose"
